name: newsroom
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.5.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  http: ^0.12.0+4 
  flutter_secure_storage: ^3.3.3
  flutter_markdown: ^0.5.1
  url_launcher: ^5.7.10
  provider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  assets: 
     - image/logo.png
     - image/icon.png
  uses-material-design: true
  fonts:
  - family: OpenSans
    fonts:
        - asset: fonts/OpenSans-Light.ttf  
  - family: Montserrat
    fonts:
        - asset: fonts/Montserrat-Bold.ttf
  - family: OpenSansBold
    fonts:
        - asset: fonts/OpenSans-SemiBold.ttf
 


