name: findadoctor
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.5.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.0.1
  http: ^0.12.0+4 
  flutter_secure_storage: ^3.3.3


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  assets: 
     - image/logo.png
     - image/icon.png
  uses-material-design: true
  fonts:
  - family: Pacifico
    fonts:
        - asset: fonts/Pacifico-Regular.ttf  
  - family: Monserrat
    fonts:
        - asset: fonts/Montserrat-Regular.ttf
  - family: Raleway
    fonts:
        - asset: fonts/Raleway-Regular.ttf
  - family: OpenSans
    fonts: 
        - asset: fonts/OpenSans-ExtraBold.ttf


